ktor {
  development = false

  environment {
    development = false
  }

  deployment {
    environment = "test"
    host = 127.0.0.1
    port = 8080

    shutdownGracePeriod = 50
    shutdownTimeout = 100

    autoreload = false
  }

  application {
    id = "Funktor-All | Test"
    modules = [io.peekandpoke.funktor.ServerKt.module]
  }
}

funktor {
  auth {
    jwt {
      issuer = ${ktor.application.id}
      audience = "api"
      signingKey = "ka2fEBWhmjPFpaPhg5Iir6tAX1COT0lGNKbD3L5SqP1WecegFVr8vduPy5CdeVNmNQ0oo7b1LgeiNomzLLy51Yt7CW320q8df6Je9ULtkgnPvZ0fpovQmz0spYJCuYFKYxNkFuO5B214or6IEXDs7M3szXZD9taqTspW8jR6plA="
      permissionsNs = "permissions"
      userNs = "user"
    }
  }

  vault {
    profile: false
    explain: false
  }
}
