include required("application.common.conf")
include "dev.overrides.conf"

ktor {
  development = false

  deployment {
    environment = "dev"
    host = 127.0.0.1
    port = 36587

    shutdownGracePeriod = 50
    shutdownTimeout = 100

    autoreload = false
    # watch = ["build/classes"]
  }

  application {
    id = "Funktor-Demo | Dev"
  }
}

funktor {
  auth {
    jwt {
      keys = [
        { id = "dev-1", secret = ${JWT_SIGNING_KEY}, alg = "HS512", issued = "2026-08-01" }
      ]
    }
    baseUrls {
      admin = "http://admin.funktor-demo.localhost:36588"
      ops = "http://ops.funktor-demo.localhost:36590"
      b2b = "http://b2b.funktor-demo.localhost:36591"
      b2b2c = "http://b2b2c.funktor-demo.localhost:36592"
    }
  }

  vault {
    profile: true
    explain: true
  }
}

admin {
  baseUrl = "http://admin.funktor-demo.localhost:36588"
}

api {
  baseUrl = "http://api.funktor-demo.localhost:36587"
  insights {
    enabled = true
  }
}

arangodb {
  user: "root"
  password: ""
  host: "localhost"
  port: 8529
  database: "funktor-demo-dev"
}

mongodb {
  connectionString = "mongodb://root:root@localhost:27017"
  database = "funktor-demo-dev"
}
