package io.peekandpoke.ultra.codegen.ts

import io.peekandpoke.ultra.codegen.printer.CodePrinter

/**
 * Emits `index.ts`, which re-exports every other emitted module.
 *
 * So a caller writes `import { FunktorConfClient } from '@sdk'` instead of knowing which file a
 * symbol lives in.
 *
 * **`export *` rather than a curated list.** The builder does not know what a contributor's file
 * declares, and a hand-maintained list would silently fall behind the moment someone adds an export.
 *
 * The cost is worth stating plainly: a NAME COLLISION between two emitted files stops being
 * harmless. Today `models.ts` and a client file could both export `Foo` and nothing would notice,
 * because nothing imports both. Through a barrel that is an error — so `ts-verify` compiles the
 * barrel deliberately, to surface it here rather than in a consumer's build.
 *
 * **Individual files stay importable.** A barrel that becomes the only door defeats tree-shaking in
 * bundlers that cannot see through re-exports, so this is an ergonomic addition, not a funnel.
 */
object TsBarrelEmitter {

    /** The barrel's path, relative to the SDK root. */
    const val PATH: String = "index.ts"

    /**
     * Renders a barrel re-exporting [paths].
     *
     * [PATH] is excluded if present — a module cannot re-export itself — and the result is SORTED, so
     * the file is stable across runs. `--check` compares content, and an unstable order would report
     * drift that is not real.
     */
    fun emit(paths: Collection<String>): String = CodePrinter.print {
        appendLine("// Generated by ultra:codegen. Do not edit — regenerate with `sdk:ts:generate`.")
        nl()

        paths
            .filter { it.endsWith(".ts") && it != PATH }
            .distinct()
            .sorted()
            .forEach { path -> appendLine("export * from ${tsStringLiteral("./$path")}") }
    }
}
