package io.peekandpoke.ultra.codegen.ts

import io.peekandpoke.ultra.codegen.model.TsTypeRef
import io.peekandpoke.ultra.codegen.model.TypeModel
import io.peekandpoke.ultra.codegen.printer.CodePrinter

/**
 * A client to emit, described without reference to where its endpoints came from.
 *
 * Deliberately framework-neutral: the funktor REST contributor builds one of these from an
 * `ApiFeature`, but so could a contributor over any other route description. Keeping the SHAPE here
 * and the WALK there is also what puts the emitted TypeScript under `ts-verify`, which lives in this
 * module — a renderer that could only be exercised from `funktor/codegen` would need a second copy of
 * the whole toolchain to prove anything.
 */
data class TsClientSpec(
    /** The aggregate class, e.g. `FunktorConfClient`. */
    val className: String,
    /** Where it is emitted, relative to the SDK root, e.g. `funktorConfClient.ts`. */
    val fileName: String,
    /** TSDoc for the aggregate, one line. */
    val doc: String?,
    val groups: List<Group>,
) {
    /** One group of endpoints — an `ApiRoutes` group on the funktor side. */
    data class Group(
        /** The class carrying the endpoints, e.g. `FunktorConfApi`. */
        val className: String,
        /** The aggregate's member for this group, e.g. `funktorConf`. */
        val member: String,
        val doc: String?,
        val endpoints: List<Endpoint>,
    )

    /** One endpoint. */
    data class Endpoint(
        /** The member name, e.g. `listEvents`. */
        val member: String,
        /** Uppercase HTTP method, e.g. `GET`. */
        val httpMethod: String,
        /** The route pattern with `{name}` placeholders, passed through to `buildUrl`. */
        val pattern: String,
        /**
         * The RESPONSE PAYLOAD's reference — not the envelope's.
         *
         * `ApiResponse<T>` is hand-written in `runtime/apiResponse.ts` and no walk reaches it; the
         * generated call wraps this payload schema at run time.
         */
        val responseRef: TsTypeRef,
        val doc: String?,
        /** Parameters filling `{name}` placeholders in [pattern]. */
        val pathParams: List<Param> = emptyList(),
        /** Parameters appended to the query string. */
        val queryParams: List<Param> = emptyList(),
    ) {
        /** Every parameter, in one object as the caller sees it. */
        val allParams: List<Param> get() = pathParams + queryParams
    }

    /**
     * One URL parameter.
     *
     * [tsType] is the type ON THE WIRE, already rendered — a URL parameter is not JSON, so it is not
     * a [TsTypeRef]. Whoever builds the spec owns that mapping, because it depends on the server's
     * parameter converters rather than on TypeScript.
     */
    data class Param(
        val name: String,
        val tsType: String,
        /** True when the Kotlin constructor parameter has a default, so the caller may omit it. */
        val optional: Boolean,
    )
}

/**
 * Renders a [TsClientSpec] as TypeScript.
 *
 * Two shape decisions are load-bearing and were settled by running the pinned compiler, not by
 * reasoning:
 *
 * - **Members are arrow-function class fields, never prototype methods.** A prototype method
 *   type-checks when destructured and throws at run time; `const { getEvent } = client.conf` is the
 *   Vue-composable idiom, so that is wrong-and-quiet. Class fields are standard JS, so they also
 *   survive `erasableSyntaxOnly` and Node's type stripping.
 * - **The constructor declares a field and assigns it.** A parameter property
 *   (`constructor(private readonly config: SdkConfig)`) is **TS1294** under `erasableSyntaxOnly`.
 */
class TsClientEmitter(private val model: TypeModel) {

    private val renderer = TsRenderer(model)

    /** Renders [spec] as a complete TypeScript module. */
    fun emit(spec: TsClientSpec): String {
        val endpoints = spec.groups.flatMap { it.endpoints }

        val schemas = endpoints.associate { it.member to renderer.schema(it.responseRef) }

        val referenced = endpoints.flatMap { it.responseRef.referencedIds() }.distinct()

        // A claimed type is NOT exported by models.ts — it is imported into it from the module that
        // owns it, so a client referencing one must import it from that module too. Getting this
        // wrong emits a name models.ts never exported, which only `tsc` would catch.
        val (claimed, declared) = referenced.partition { id ->
            model.usedClaims.containsKey(id.cls.qualifiedName)
        }

        val modelNames = declared.map { renderer.nameOf(it) }.distinct().sorted()

        val claimImports = claimed
            .mapNotNull { model.usedClaims[it.cls.qualifiedName] }
            .filter { !it.opaque && it.importFrom != null }
            .groupBy { it.importFrom!! }
            .toSortedMap()

        return CodePrinter.print {
            appendLine("// Generated by ultra:codegen. Do not edit — regenerate with `sdk:ts:generate`.")
            nl()

            // `z.` only appears for containers (arrays, records, nullables), so a client returning
            // only declared objects must not carry an unused zod import.
            if (schemas.values.any { it.contains("z.") }) {
                appendLine("import { z } from 'zod'")
            }

            appendLine("import { type SdkConfig, request } from ${tsStringLiteral(CLIENT_MODULE)}")

            if (modelNames.isNotEmpty()) {
                appendLine("import { ${modelNames.joinToString(", ")} } from ${tsStringLiteral(MODELS_MODULE)}")
            }

            claimImports.forEach { (module, claims) ->
                val names = claims.flatMap { listOfNotNull(it.tsName, it.schema) }.distinct().sorted()
                appendLine("import { ${names.joinToString(", ")} } from ${tsStringLiteral(module)}")
            }

            spec.groups.forEach { group ->
                nl()
                appendGroup(group, schemas)
            }

            nl()
            appendAggregate(spec)
        }
    }

    private fun CodePrinter.appendGroup(group: TsClientSpec.Group, schemas: Map<String, String>) {
        group.doc?.let { appendLine("/** ${it.oneLine()} */") }

        appendLine("export class ${group.className} {")

        indentedRaw {
            appendLine("private readonly config: SdkConfig")
            nl()
            appendLine("constructor(config: SdkConfig) {")
            indentedRaw { appendLine("this.config = config") }
            appendLine("}")

            group.endpoints.forEach { endpoint ->
                nl()
                endpoint.doc?.let { appendLine("/** ${it.oneLine()} */") }
                appendEndpoint(endpoint, schemas.getValue(endpoint.member))
            }
        }

        appendLine("}")
    }

    /**
     * One endpoint member.
     *
     * Path and query parameters are taken as ONE object, mirroring the Kotlin PARAMS class the caller
     * would fill in — which side of the URL each lands on is the route pattern's business, not the
     * caller's — and split back apart in the call. Their names cannot collide: they are properties of
     * a single class.
     */
    private fun CodePrinter.appendEndpoint(endpoint: TsClientSpec.Endpoint, schema: String) {
        val params = endpoint.allParams

        val signature = when {
            params.isEmpty() -> "()"

            else -> params.joinToString(separator = "; ", prefix = "(params: { ", postfix = " })") {
                "${it.name}${if (it.optional) "?" else ""}: ${it.tsType}"
            }
        }

        appendLine("readonly ${endpoint.member} = $signature =>")

        indentedRaw {
            val call = "request(this.config, ${tsStringLiteral(endpoint.httpMethod)}, " +
                    "${tsStringLiteral(endpoint.pattern)}, $schema"

            if (params.isEmpty()) {
                appendLine("$call)")
                return@indentedRaw
            }

            appendLine("$call, {")

            indentedRaw {
                listOf("path" to endpoint.pathParams, "query" to endpoint.queryParams)
                    .filter { (_, group) -> group.isNotEmpty() }
                    .forEach { (key, group) ->
                        appendLine(
                            group.joinToString(", ", "$key: { ", " },") { "${it.name}: params.${it.name}" }
                        )
                    }
            }

            appendLine("})")
        }
    }

    private fun CodePrinter.appendAggregate(spec: TsClientSpec) {
        spec.doc?.let { appendLine("/** ${it.oneLine()} */") }

        appendLine("export class ${spec.className} {")

        indentedRaw {
            spec.groups.forEach { group ->
                appendLine("readonly ${group.member}: ${group.className}")
            }

            nl()
            appendLine("constructor(config: SdkConfig) {")
            indentedRaw {
                spec.groups.forEach { group ->
                    appendLine("this.${group.member} = new ${group.className}(config)")
                }
            }
            appendLine("}")
        }

        appendLine("}")
    }

    /** Collapses [this] to a single line, so a multi-line description cannot break out of `/** */`. */
    private fun String.oneLine(): String = trim()
        .lineSequence()
        .joinToString(" ") { it.trim() }
        .replace("*/", "* /")

    companion object {
        private val CLIENT_MODULE: String = TsRuntime.Module.Client.moduleSpecifier

        /** Where the type declarations live. Emitted by `TsSdkBuilder`, at the SDK root. */
        private const val MODELS_MODULE: String = "./models.ts"
    }
}
