package io.peekandpoke.ultra.codegen.ts

import io.peekandpoke.ultra.codegen.model.TsTypeDecl
import io.peekandpoke.ultra.codegen.model.TypeId
import io.peekandpoke.ultra.codegen.model.TypeModel
import io.peekandpoke.ultra.codegen.printer.CodePrinter

/**
 * Emits every declared type into a single `models.ts`.
 *
 * One file rather than one per Kotlin package, deliberately: a zod schema is a `const`, so a
 * cross-file cycle would be a circular VALUE import and blow up at module-evaluation time. Keeping
 * the models together reduces the ordering problem to one file, where [TsDeclOrder] solves it
 * outright. Splitting later is possible, but only with `z.lazy` on every cross-file edge.
 */
class TsModelEmitter(
    private val model: TypeModel,
    private val header: String = DEFAULT_HEADER,
) {
    companion object {
        const val DEFAULT_HEADER: String =
            "// Generated by ultra:codegen. Do not edit — regenerate with `sdk:ts:generate`."
    }

    private val renderer = TsRenderer(model)

    private val order = TsDeclOrder.of(model)

    fun emit(): String = CodePrinter.print {
        appendLine(header)
        nl()

        appendImports()

        appendEach(order.ordered, separator = { nl(2) }) { decl -> appendDecl(decl) }
        nl()
    }

    private fun CodePrinter.appendImports() {
        appendLine("import { z } from 'zod'")

        // A claim with no module needs no import — it is either ambient or an inline expression.
        val byModule = model.usedClaims.values
            .filter { !it.opaque && it.importFrom != null }
            .groupBy { it.importFrom!! }
            .toSortedMap()

        byModule.forEach { (module, claims) ->
            val names = claims
                .flatMap { listOfNotNull(it.tsName, it.schema) }
                .distinct()
                .sorted()

            appendLine("import { ${names.joinToString(", ")} } from '$module'")
        }

        nl()
    }

    private fun CodePrinter.appendDecl(decl: TsTypeDecl) {
        when (decl) {
            is TsTypeDecl.EnumDecl -> appendEnum(decl)
            is TsTypeDecl.Alias -> appendAlias(decl)
            is TsTypeDecl.Obj -> appendObj(decl)
            is TsTypeDecl.Union -> appendUnion(decl)
        }
    }

    /** Enums cannot be recursive, so they always use the simple inferred form. */
    private fun CodePrinter.appendEnum(decl: TsTypeDecl.EnumDecl) {
        val values = decl.values.joinToString(", ") { "'$it'" }

        appendLine("export const ${decl.name} = z.enum([$values])")
        append("export type ${decl.name} = z.infer<typeof ${decl.name}>")
    }

    private fun CodePrinter.appendAlias(decl: TsTypeDecl.Alias) {
        appendLine("export const ${decl.name} = ${renderer.schema(decl.target)}")
        append("export type ${decl.name} = z.infer<typeof ${decl.name}>")
    }

    private fun CodePrinter.appendObj(decl: TsTypeDecl.Obj) {
        val recursive = order.isRecursive(decl.id)

        if (recursive) {
            // z.infer cannot see through z.lazy, so the type is written out instead of inferred.
            appendLine("export type ${decl.name} = {").indentedRaw {
                appendObjTypeBody(decl)
            }
            appendLine("}")
        }

        val schemaHead = when {
            recursive -> "export const ${decl.name}: z.ZodType<${decl.name}> = z.lazy(() => z.object({"
            else -> "export const ${decl.name} = z.object({"
        }

        appendLine(schemaHead).indentedRaw {
            appendObjSchemaBody(decl)
        }

        append(if (recursive) "}))" else "})")

        if (!recursive) {
            nl()
            append("export type ${decl.name} = z.infer<typeof ${decl.name}>")
        }
    }

    private fun CodePrinter.appendObjTypeBody(decl: TsTypeDecl.Obj) {
        decl.discriminator?.let {
            appendLine("${it.field}: '${it.literal}'")
        }

        decl.props.forEach { prop ->
            val optional = if (prop.optional) "?" else ""
            appendLine("${quoteIfNeeded(prop.name)}$optional: ${renderer.type(prop.type)}")
        }
    }

    private fun CodePrinter.appendObjSchemaBody(decl: TsTypeDecl.Obj) {
        decl.discriminator?.let {
            appendLine("${it.field}: z.literal('${it.literal}'),")
        }

        decl.props.forEach { prop ->
            val optional = if (prop.optional) ".optional()" else ""
            appendLine("${quoteIfNeeded(prop.name)}: ${renderer.schema(prop.type)}$optional,")
        }
    }

    private fun CodePrinter.appendUnion(decl: TsTypeDecl.Union) {
        val variants = decl.variants.map { renderer.nameOf(it) }

        // z.discriminatedUnion needs its options to be concrete object schemas at construction, so a
        // lazily-emitted variant rules it out. z.union still works and stays correct — it just reports
        // worse errors, because it has no discriminator to narrow on.
        val anyLazy = decl.variants.any { order.isRecursive(it) } || order.isRecursive(decl.id)

        val schema = when {
            anyLazy -> "z.union([${variants.joinToString(", ")}])"
            else -> "z.discriminatedUnion('${decl.discriminatorField}', [${variants.joinToString(", ")}])"
        }

        if (order.isRecursive(decl.id)) {
            appendLine("export type ${decl.name} = ${variants.joinToString(" | ")}")
            appendLine("export const ${decl.name}: z.ZodType<${decl.name}> = z.lazy(() => $schema)")
            return
        }

        appendLine("export const ${decl.name} = $schema")
        append("export type ${decl.name} = z.infer<typeof ${decl.name}>")
    }

    /** Quotes a property name that is not a valid bare TypeScript identifier. */
    private fun quoteIfNeeded(name: String): String = when {
        name.matches(Regex("[A-Za-z_$][A-Za-z0-9_$]*")) -> name
        else -> "'$name'"
    }

    /** Ids that were emitted, for callers that want to cross-check coverage. */
    fun emittedIds(): List<TypeId> = order.ordered.map { it.id }
}
