package io.peekandpoke.ultra.codegen.ts

import io.peekandpoke.ultra.codegen.printer.CodePrinter
import io.peekandpoke.ultra.codegen.sdk.TsSdkRegistry

/**
 * Renders `mount.ts` — the page routes contributors registered, plus a bulk mounting helper.
 *
 * **The SDK never mounts itself.** The generator owns its output directory and wipes it every run, so
 * it can write nothing into the consuming app; mounting is therefore something the app does, by hand,
 * once. [PATH] exists so that hand-written line is one call rather than N.
 *
 * ```ts
 * import { mountAll } from './funktorsdk/mount.ts'
 * mountAll(router)
 * ```
 *
 * **No `vue-router` import.** `MountTarget` is declared structurally, so a real `Router` satisfies
 * it without this module — or `ultra:codegen`'s verification toolchain — depending on Vue. An app
 * that wants something other than bulk mounting reads `routes` and does its own thing.
 */
object TsMountEmitter {

    /** Where it is emitted, relative to the SDK root. */
    const val PATH: String = "mount.ts"

    /**
     * The `HttpMethod` union, rendered from the set `TsSdkRegistry` validates against.
     *
     * DERIVED rather than written out, so the emitted type and the check that guards it cannot say
     * different things — the failure would be a nav entry that passes generation and then breaks
     * `tsc` inside output the consuming app cannot edit.
     */
    private val HTTP_METHOD_UNION: String =
        TsClientSpec.Endpoint.KNOWN_HTTP_METHODS.joinToString(" | ") { tsStringLiteral(it) }

    /** Renders the aggregate for [routes]. */
    fun emit(routes: List<TsSdkRegistry.Route>, navRoutes: List<TsSdkRegistry.Route>): String =
        CodePrinter.print {
            appendLine("// Generated by ultra:codegen. Do not edit — regenerate with `sdk:ts:generate`.")
            nl()

            appendDocs()
            nl()

            appendLine("export const routes: readonly SdkRoute[] = [")
            indentedRaw {
                routes.forEach { route ->
                    // A LAZY import, not a static one: a page the user never visits must not be in
                    // the entry chunk, and a router table that eagerly imports every page defeats
                    // code-splitting for the whole app.
                    appendLine("{")
                    indentedRaw {
                        appendLine("path: ${tsStringLiteral(route.path)},")
                        appendLine("component: () => import(${tsStringLiteral("./${route.component}")}),")
                        appendLine("meta: { requiresAuth: ${route.requiresAuth} },")
                    }
                    appendLine("},")
                }
            }
            appendLine("] as const")
            nl()

            appendLine("export const navItems: readonly SdkNavItem[] = [")
            indentedRaw {
                navRoutes.forEach { route ->
                    val nav = route.nav!!

                    appendLine("{")
                    indentedRaw {
                        appendLine("path: ${tsStringLiteral(route.path)},")
                        appendLine("label: ${tsStringLiteral(nav.label)},")
                        appendLine("icon: ${nav.icon?.let { tsStringLiteral(it) } ?: "null"},")
                        appendLine("requiresAuth: ${route.requiresAuth},")
                        appendRequires(nav.requires)
                    }
                    appendLine("},")
                }
            }
            appendLine("] as const")
            nl()

            appendMountAll()
        }

    private fun CodePrinter.appendDocs() {
        appendLine("/** A page route contributed by the SDK. */")
        appendLine("export interface SdkRoute {")
        indentedRaw {
            appendLine("readonly path: string")
            appendLine("/** Lazy so an unvisited page stays out of the entry chunk. */")
            appendLine("readonly component: () => Promise<unknown>")
            appendLine("readonly meta: { readonly requiresAuth: boolean }")
        }
        appendLine("}")
        nl()

        appendLine("/**")
        appendLine(" * An API route a nav entry's page cannot function without.")
        appendLine(" *")
        appendLine(" * Structurally identical to `RouteRef` in `runtime/route.ts`, so `ApiAcl.canAccess`")
        appendLine(" * takes one unchanged. DECLARED here rather than imported: runtime modules ship only")
        appendLine(" * when something imports them, and this file is emitted unconditionally — so an")
        appendLine(" * import would break every SDK that reaches no API client at all.")
        appendLine(" *")
        appendLine(" * The name differs from `RouteRef` on purpose. The barrel `export *`s both this file")
        appendLine(" * and `runtime/route.ts`, and two exports of one name there is a hard TS2308.")
        appendLine(" */")
        appendLine("export interface SdkApiRouteRef {")
        indentedRaw {
            appendLine("readonly method: $HTTP_METHOD_UNION")
            appendLine("/** The route PATTERN, placeholders included — the form the access matrix is keyed on. */")
            appendLine("readonly uri: string")
            appendLine("/** The server admits an anonymous caller; `ApiAcl.canAccess` short-circuits on it. */")
            appendLine("readonly isPublic: boolean")
        }
        appendLine("}")
        nl()

        appendLine("/** A navigation entry pointing at one of [routes]. */")
        appendLine("export interface SdkNavItem {")
        indentedRaw {
            appendLine("readonly path: string")
            appendLine("readonly label: string")
            appendLine("readonly icon: string | null")
            appendLine("readonly requiresAuth: boolean")
            appendLine("/**")
            appendLine(" * API routes the page needs. **ALL must be accessible** for the entry to show;")
            appendLine(" * empty means it is never hidden on access grounds.")
            appendLine(" *")
            appendLine(" * ```ts")
            appendLine(" * navItems.filter((i) => i.requires.every((r) => acl.canAccess(r)))")
            appendLine(" * ```")
            appendLine(" *")
            appendLine(" * ADVISORY, like everything built on the matrix: this decides what to RENDER.")
            appendLine(" * The server is the authority, and the route guard deliberately ignores this —")
            appendLine(" * a user who types the URL still reaches the page and it 403s honestly.")
            appendLine(" */")
            appendLine("readonly requires: readonly SdkApiRouteRef[]")
        }
        appendLine("}")
        nl()

        appendLine("/**")
        appendLine(" * The part of a router [mountAll] needs.")
        appendLine(" *")
        appendLine(" * Structural on purpose: a `vue-router` `Router` satisfies it, and the SDK stays")
        appendLine(" * framework-neutral — which is also what lets it be type-checked and executed without")
        appendLine(" * Vue installed.")
        appendLine(" */")
        appendLine("export interface MountTarget {")
        indentedRaw { appendLine("addRoute(route: SdkRoute): unknown") }
        appendLine("}")
    }

    /**
     * Renders a nav entry's [TsSdkRegistry.Nav.requires].
     *
     * Empty collapses to `[]` on one line — the overwhelmingly common case, and a three-line empty
     * array in every entry would bury the two that carry one.
     */
    private fun CodePrinter.appendRequires(requires: List<TsSdkRegistry.ApiRouteRef>) {
        if (requires.isEmpty()) {
            appendLine("requires: [],")
            return
        }

        appendLine("requires: [")
        indentedRaw {
            requires.forEach { ref ->
                appendLine(
                    "{ method: ${tsStringLiteral(ref.method)}, " +
                            "uri: ${tsStringLiteral(ref.uri)}, " +
                            "isPublic: ${ref.isPublic} },"
                )
            }
        }
        appendLine("],")
    }

    private fun CodePrinter.appendMountAll() {
        appendLine("/**")
        appendLine(" * Adds every contributed route to [target].")
        appendLine(" *")
        appendLine(" * Bulk convenience. For anything selective — a subset, a parent route, a different")
        appendLine(" * layout — read [routes] and call `addRoute` yourself; this is not a funnel.")
        appendLine(" *")
        appendLine(" * `addRoute` at run time rather than a static array is what keeps the app's own router")
        appendLine(" * file untouched: the generator wipes and rewrites its own directory every run and")
        appendLine(" * writes nothing outside it.")
        appendLine(" */")
        appendLine("export function mountAll(target: MountTarget): void {")
        indentedRaw { appendLine("for (const route of routes) target.addRoute(route)") }
        appendLine("}")
    }
}
