package io.peekandpoke.ultra.codegen.ts

import io.peekandpoke.ultra.codegen.model.TsTypeDecl
import io.peekandpoke.ultra.codegen.model.TypeId
import io.peekandpoke.ultra.codegen.model.TypeModel
import io.peekandpoke.ultra.codegen.printer.CodePrinter

/**
 * Emits every declared type into a single `models.ts`.
 *
 * One file rather than one per Kotlin package, deliberately: a zod schema is a `const`, so a
 * cross-file cycle would be a circular VALUE import and blow up at module-evaluation time. Keeping
 * the models together reduces the ordering problem to one file, where [TsDeclOrder] solves it
 * outright. Splitting later is possible, but only with `z.lazy` on every cross-file edge.
 */
class TsModelEmitter(
    private val model: TypeModel,
    private val header: String = DEFAULT_HEADER,
) {
    companion object {
        const val DEFAULT_HEADER: String =
            "// Generated by ultra:codegen. Do not edit — regenerate with `sdk:ts:generate`."
    }

    private val renderer = TsRenderer(model)

    private val order = TsDeclOrder.of(model)

    fun emit(): String = CodePrinter.print {
        appendLine(header)
        nl()

        appendImports()

        appendEach(order.ordered, separator = { nl(2) }) { decl -> appendDecl(decl) }
        nl()
    }

    private fun CodePrinter.appendImports() {
        appendLine("import { z } from 'zod'")

        // A claim with no module needs no import — it is either ambient or an inline expression.
        val byModule = model.usedClaims.values
            .filter { !it.opaque && it.importFrom != null }
            .groupBy { it.importFrom!! }
            .toSortedMap()

        byModule.forEach { (module, claims) ->
            val names = claims
                .flatMap { listOfNotNull(it.tsName, it.schema) }
                .distinct()
                .sorted()

            appendLine("import { ${names.joinToString(", ")} } from ${tsStringLiteral(module)}")
        }

        nl()
    }

    private fun CodePrinter.appendDecl(decl: TsTypeDecl) {
        when (decl) {
            is TsTypeDecl.EnumDecl -> appendEnum(decl)
            is TsTypeDecl.Alias -> appendAlias(decl)
            is TsTypeDecl.Obj -> appendObj(decl)
            is TsTypeDecl.Union -> appendUnion(decl)
        }
    }

    /** Enums cannot be recursive, so they always use the simple inferred form. */
    private fun CodePrinter.appendEnum(decl: TsTypeDecl.EnumDecl) {
        val values = decl.values.joinToString(", ") { tsStringLiteral(it) }

        appendLine("export const ${decl.name} = z.enum([$values])")
        append("export type ${decl.name} = z.infer<typeof ${decl.name}>")
    }

    private fun CodePrinter.appendAlias(decl: TsTypeDecl.Alias) {
        if (decl.typeParams.isNotEmpty()) {
            val params = decl.typeParams.joinToString(", ")

            val schemaArgs = decl.typeParams.joinToString(", ") {
                "${renderer.schemaParamOf(it)}: z.ZodType<$it>"
            }

            appendLine("export type ${decl.name}<$params> = ${renderer.type(decl.target)}")
            appendLine(
                "export const ${decl.name} = <$params>($schemaArgs)" +
                        ": z.ZodType<${decl.name}<$params>> =>"
            )
            indentedRaw { append(renderer.schema(decl.target)) }
            return
        }

        // An alias can sit on a cycle — `value class FxIds(val items: List<FxHolder>)` where
        // `FxHolder.ids: FxIds` — and a zod schema is a const, so an eager forward reference is a
        // temporal-dead-zone error at module evaluation, not merely a compile warning.
        if (order.isRecursive(decl.id)) {
            appendLine("export type ${decl.name} = ${renderer.type(decl.target)}")
            append(
                "export const ${decl.name}: z.ZodType<${decl.name}> = " +
                        "z.lazy(() => ${renderer.schema(decl.target)})"
            )
            return
        }

        appendLine("export const ${decl.name} = ${renderer.schema(decl.target)}")
        append("export type ${decl.name} = z.infer<typeof ${decl.name}>")
    }

    private fun CodePrinter.appendObj(decl: TsTypeDecl.Obj) {
        if (decl.typeParams.isNotEmpty()) {
            appendGenericObj(decl)
            return
        }

        val recursive = order.isRecursive(decl.id)

        if (recursive) {
            // z.infer cannot see through z.lazy, so the type is written out instead of inferred.
            appendLine("export type ${decl.name} = {").indentedRaw {
                appendObjTypeBody(decl)
            }
            appendLine("}")
        }

        val schemaHead = when {
            recursive -> "export const ${decl.name}: z.ZodType<${decl.name}> = z.lazy(() => z.object({"
            else -> "export const ${decl.name} = z.object({"
        }

        appendLine(schemaHead).indentedRaw {
            appendObjSchemaBody(decl)
        }

        append(if (recursive) "}))" else "})")

        if (!recursive) {
            nl()
            append("export type ${decl.name} = z.infer<typeof ${decl.name}>")
        }
    }

    /**
     * A generic object: an interface plus a schema FACTORY.
     *
     * The two share one identifier — TypeScript keeps types and values in separate namespaces, so
     * `interface PageOf<T>` and `const PageOf` coexist, exactly as the non-generic form's
     * `export const X` and `export type X` do.
     *
     * `z.infer` is not used here. It CAN see through a factory via an instantiation expression
     * (measured — see the generics spike), but spelling the interface out keeps the emitted type
     * readable and gives the factory's return type something to name.
     */
    private fun CodePrinter.appendGenericObj(decl: TsTypeDecl.Obj) {
        val params = decl.typeParams.joinToString(", ")

        val schemaArgs = decl.typeParams.joinToString(", ") {
            "${renderer.schemaParamOf(it)}: z.ZodType<$it>"
        }

        val self = "${decl.name}<$params>"

        appendLine("export interface ${decl.name}<$params> {").indentedRaw {
            appendObjTypeBody(decl)
        }
        appendLine("}")

        // A generic declaration on a cycle still needs deferring, for the same reason a plain one does:
        // the factory body would otherwise reference a const that is not initialised yet.
        val lazy = order.isRecursive(decl.id)

        // ANNOTATING the return type erases the schema's object-ness, and `z.discriminatedUnion`
        // requires concrete object options — so an annotated variant factory fails to type-check as a
        // union option (measured: TS2322). `satisfies` checks the schema against the interface while
        // keeping the narrower inferred type, which is what the union needs.
        //
        // A recursive one has no choice: `z.lazy` cannot infer its own result, so it must be annotated.
        // That is the same trade the non-generic path already makes, and a lazy variant already forces
        // its union onto `z.union` regardless.
        if (lazy) {
            appendLine("export const ${decl.name} = <$params>($schemaArgs): z.ZodType<$self> =>")

            indentedRaw {
                appendLine("z.lazy(() => z.object({").indentedRaw {
                    appendObjSchemaBody(decl)
                }
                append("}))")
            }

            return
        }

        appendLine("export const ${decl.name} = <$params>($schemaArgs) =>")

        indentedRaw {
            appendLine("z.object({").indentedRaw {
                appendObjSchemaBody(decl)
            }
            append("}) satisfies z.ZodType<$self>")
        }
    }

    private fun CodePrinter.appendObjTypeBody(decl: TsTypeDecl.Obj) {
        decl.discriminator?.let {
            appendLine("${tsPropertyName(it.field)}: ${tsStringLiteral(it.literal)}")
        }

        decl.props.forEach { prop ->
            val optional = if (prop.optional) "?" else ""
            appendLine("${tsPropertyName(prop.name)}$optional: ${renderer.type(prop.type)}")
        }
    }

    private fun CodePrinter.appendObjSchemaBody(decl: TsTypeDecl.Obj) {
        decl.discriminator?.let {
            appendLine("${tsPropertyName(it.field)}: z.literal(${tsStringLiteral(it.literal)}),")
        }

        decl.props.forEach { prop ->
            val optional = if (prop.optional) ".optional()" else ""
            appendLine("${tsPropertyName(prop.name)}: ${renderer.schema(prop.type)}$optional,")
        }
    }

    private fun CodePrinter.appendUnion(decl: TsTypeDecl.Union) {
        // Two lists, not one. For a DECLARATION the type and the schema share a name — that is the zod
        // pattern, `export const X` beside `export type X`. For a CLAIM they need not: `JsonElement` is
        // claimed as the type `unknown` with the schema `z.unknown()`. Using the type name inside
        // z.union/z.discriminatedUnion emits a type where a value is required.
        val typeNames = decl.variants.map { renderer.type(it) }
        val schemaNames = decl.variants.map { renderer.schema(it) }

        // z.discriminatedUnion needs its options to be concrete object schemas at construction, so a
        // lazily-emitted variant rules it out. z.union still works and stays correct — it just reports
        // worse errors, because it has no discriminator to narrow on.
        val anyLazy = decl.variants.any { order.isRecursive(it.id) } || order.isRecursive(decl.id)

        val schema = when {
            anyLazy -> "z.union([${schemaNames.joinToString(", ")}])"
            else ->
                "z.discriminatedUnion(${tsStringLiteral(decl.discriminatorField)}, " +
                        "[${schemaNames.joinToString(", ")}])"
        }

        if (decl.typeParams.isNotEmpty()) {
            val params = decl.typeParams.joinToString(", ")

            val schemaArgs = decl.typeParams.joinToString(", ") {
                "${renderer.schemaParamOf(it)}: z.ZodType<$it>"
            }

            appendLine("export type ${decl.name}<$params> = ${typeNames.joinToString(" | ")}")
            appendLine(
                "export const ${decl.name} = <$params>($schemaArgs)" +
                        ": z.ZodType<${decl.name}<$params>> =>"
            )
            indentedRaw { append(schema) }
            return
        }

        if (order.isRecursive(decl.id)) {
            appendLine("export type ${decl.name} = ${typeNames.joinToString(" | ")}")
            appendLine("export const ${decl.name}: z.ZodType<${decl.name}> = z.lazy(() => $schema)")
            return
        }

        appendLine("export const ${decl.name} = $schema")
        append("export type ${decl.name} = z.infer<typeof ${decl.name}>")
    }

    /** Ids that were emitted, for callers that want to cross-check coverage. */
    fun emittedIds(): List<TypeId> = order.ordered.map { it.id }
}
