package io.peekandpoke.ultra.codegen.ts

import io.peekandpoke.ultra.codegen.printer.CodePrinter
import io.peekandpoke.ultra.codegen.sdk.TsSdkRegistry

/**
 * Renders `mount.ts` — the page routes contributors registered, plus a bulk mounting helper.
 *
 * **The SDK never mounts itself.** The generator owns its output directory and wipes it every run, so
 * it can write nothing into the consuming app; mounting is therefore something the app does, by hand,
 * once. [PATH] exists so that hand-written line is one call rather than N.
 *
 * ```ts
 * import { mountAll } from './funktorsdk/mount.ts'
 * mountAll(router)
 * ```
 *
 * **No `vue-router` import.** [MOUNT_TARGET] is declared structurally, so a real `Router` satisfies
 * it without this module — or `ultra:codegen`'s verification toolchain — depending on Vue. An app
 * that wants something other than bulk mounting reads `routes` and does its own thing.
 */
object TsMountEmitter {

    /** Where it is emitted, relative to the SDK root. */
    const val PATH: String = "mount.ts"

    /** Renders the aggregate for [routes]. */
    fun emit(routes: List<TsSdkRegistry.Route>, navRoutes: List<TsSdkRegistry.Route>): String =
        CodePrinter.print {
            appendLine("// Generated by ultra:codegen. Do not edit — regenerate with `sdk:ts:generate`.")
            nl()

            appendDocs()
            nl()

            appendLine("export const routes: readonly SdkRoute[] = [")
            indentedRaw {
                routes.forEach { route ->
                    // A LAZY import, not a static one: a page the user never visits must not be in
                    // the entry chunk, and a router table that eagerly imports every page defeats
                    // code-splitting for the whole app.
                    appendLine("{")
                    indentedRaw {
                        appendLine("path: ${tsStringLiteral(route.path)},")
                        appendLine("component: () => import(${tsStringLiteral("./${route.component}")}),")
                        appendLine("meta: { requiresAuth: ${route.requiresAuth} },")
                    }
                    appendLine("},")
                }
            }
            appendLine("] as const")
            nl()

            appendLine("export const navItems: readonly SdkNavItem[] = [")
            indentedRaw {
                navRoutes.forEach { route ->
                    val nav = route.nav!!

                    appendLine("{")
                    indentedRaw {
                        appendLine("path: ${tsStringLiteral(route.path)},")
                        appendLine("label: ${tsStringLiteral(nav.label)},")
                        appendLine("icon: ${nav.icon?.let { tsStringLiteral(it) } ?: "null"},")
                        appendLine("requiresAuth: ${route.requiresAuth},")
                    }
                    appendLine("},")
                }
            }
            appendLine("] as const")
            nl()

            appendMountAll()
        }

    private fun CodePrinter.appendDocs() {
        appendLine("/** A page route contributed by the SDK. */")
        appendLine("export interface SdkRoute {")
        indentedRaw {
            appendLine("readonly path: string")
            appendLine("/** Lazy so an unvisited page stays out of the entry chunk. */")
            appendLine("readonly component: () => Promise<unknown>")
            appendLine("readonly meta: { readonly requiresAuth: boolean }")
        }
        appendLine("}")
        nl()

        appendLine("/** A navigation entry pointing at one of [routes]. */")
        appendLine("export interface SdkNavItem {")
        indentedRaw {
            appendLine("readonly path: string")
            appendLine("readonly label: string")
            appendLine("readonly icon: string | null")
            appendLine("readonly requiresAuth: boolean")
        }
        appendLine("}")
        nl()

        appendLine("/**")
        appendLine(" * The part of a router [mountAll] needs.")
        appendLine(" *")
        appendLine(" * Structural on purpose: a `vue-router` `Router` satisfies it, and the SDK stays")
        appendLine(" * framework-neutral — which is also what lets it be type-checked and executed without")
        appendLine(" * Vue installed.")
        appendLine(" */")
        appendLine("export interface MountTarget {")
        indentedRaw { appendLine("addRoute(route: SdkRoute): unknown") }
        appendLine("}")
    }

    private fun CodePrinter.appendMountAll() {
        appendLine("/**")
        appendLine(" * Adds every contributed route to [target].")
        appendLine(" *")
        appendLine(" * Bulk convenience. For anything selective — a subset, a parent route, a different")
        appendLine(" * layout — read [routes] and call `addRoute` yourself; this is not a funnel.")
        appendLine(" *")
        appendLine(" * `addRoute` at run time rather than a static array is what keeps the app's own router")
        appendLine(" * file untouched: the generator wipes and rewrites its own directory every run and")
        appendLine(" * writes nothing outside it.")
        appendLine(" */")
        appendLine("export function mountAll(target: MountTarget): void {")
        indentedRaw { appendLine("for (const route of routes) target.addRoute(route)") }
        appendLine("}")
    }
}
