package io.peekandpoke.ultra.codegen.ts

import io.peekandpoke.ultra.codegen.printer.CodePrinter
import io.peekandpoke.ultra.codegen.sdk.TsSdkRegistry

/**
 * Renders `styles.ts` — one import per contributed stylesheet, in cascade order.
 *
 * **A `.css` file in the SDK directory is inert.** A bundler includes only what something imports,
 * so emitting the bytes is half the job; this is the other half, and it is the app's single entry
 * point:
 *
 * ```ts
 * import './funktorsdk/styles.ts'   // once, in main.ts, before mounting
 * ```
 *
 * **TypeScript rather than a `styles.css` full of `@import`.** Vite bundles CSS reached from JS and
 * injects it in import order, which is exactly the ordering guarantee needed here. A plain
 * stylesheet's `@import` is a request waterfall in dev, and the rule that every `@import` must
 * precede all other rules makes an aggregate fragile to edit. The app already imports TypeScript
 * from this SDK, so this also adds no new idiom.
 *
 * **A SIDE-EFFECT module**, therefore excluded from the barrel — see [TsBarrelEmitter]. If it were
 * re-exported, `import type { … } from './funktorsdk'` would pull every stylesheet into the bundle.
 */
object TsStylesEmitter {

    /** Where it is emitted, relative to the SDK root. */
    const val PATH: String = "styles.ts"

    /** The ambient declaration that makes [PATH] type-check. See [emitTypes]. */
    const val TYPES_PATH: String = "css-modules.d.ts"

    /**
     * Renders the ambient declaration, without which [PATH] does not compile at all.
     *
     * TypeScript has no idea what a `.css` module is: importing one for its side effects is
     * **TS2882, "Cannot find module or type declarations for side-effect import"**. So the aggregate
     * would break the consuming app's type-check the moment any contributor registered a sheet —
     * a mechanism that works only while unused.
     *
     * **The FILENAME is load-bearing too.** This was `styles.d.ts` first, and it silently did
     * nothing: `x.d.ts` is by convention the declaration file FOR `x.ts`, so TypeScript paired it
     * with [PATH] and never treated it as a global script. The file was present, correct, and
     * inert — TS2882 exactly as if it had not been emitted. [TYPES_PATH] must therefore not shadow
     * the basename of any emitted `.ts`.
     *
     * **The SHORTHAND form is load-bearing.** The obvious spelling —
     * `declare module '*.css' { const css: string; export default css }` — is what `vite/client`
     * already ships, and two bodied wildcard declarations are **TS2300, "Duplicate identifier"**.
     * Emitting that would break every real Vite app, which is to say every consumer. A shorthand
     * declaration has no identifiers to collide, so it works alone AND alongside `vite/client`.
     * Both cases are measured, not assumed — see `TsStylesTypesSpec`.
     */
    fun emitTypes(): String = CodePrinter.print {
        appendLine("// Generated by ultra:codegen. Do not edit — regenerate with `sdk:ts:generate`.")
        nl()
        appendLine("/**")
        appendLine(" * Lets `styles.ts` import stylesheets for their side effects.")
        appendLine(" *")
        appendLine(" * SHORTHAND on purpose. A bodied `declare module '*.css' { … }` is what")
        appendLine(" * `vite/client` ships, and two of those are a duplicate-identifier error — so the")
        appendLine(" * bodied form would break every app that has Vite's types. This one coexists.")
        appendLine(" *")
        appendLine(" * The consequence is that a `.css` import is `any` rather than typed. That costs")
        appendLine(" * nothing here: these are side-effect imports and the value is never read.")
        appendLine(" */")
        appendLine("declare module '*.css';")
    }

    /**
     * Renders the aggregate for [styles], which must already be in cascade order.
     *
     * Emitted even when empty, so the app's `import './funktorsdk/styles.ts'` compiles whether or not
     * any contributor ships CSS. A file that appears and disappears cannot be wired against.
     */
    fun emit(styles: List<TsSdkRegistry.Style>): String = CodePrinter.print {
        appendLine("// Generated by ultra:codegen. Do not edit — regenerate with `sdk:ts:generate`.")
        nl()

        appendLine("/**")
        appendLine(" * Every stylesheet this SDK ships, imported in CASCADE ORDER.")
        appendLine(" *")
        appendLine(" * Import once, before mounting the app:")
        appendLine(" *")
        appendLine(" * ```ts")
        appendLine(" * import './funktorsdk/styles.ts'")
        appendLine(" * ```")
        appendLine(" *")
        appendLine(" * The order below is the contributed order and is not arbitrary — a theme defines the")
        appendLine(" * custom properties later sheets consume. Do not reorder these lines; they are")
        appendLine(" * regenerated. Change the `order` a contributor registers with instead.")
        appendLine(" */")

        if (styles.isEmpty()) {
            appendLine("// No contributor registered a stylesheet.")
        } else {
            styles.forEach { style ->
                appendLine("import ${tsStringLiteral("./${style.path}")}")
            }
        }

        nl()
        // An `export {}` so the file is unambiguously a MODULE. Without any export or import a `.ts`
        // file is a global script under `isolatedModules`, and the empty case has no imports at all.
        appendLine("export {}")
    }
}
