package io.peekandpoke.ultra.security.jwt

import io.kotest.assertions.throwables.shouldThrow
import io.kotest.assertions.withClue
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.types.shouldBeInstanceOf
import io.peekandpoke.ultra.common.model.Redacted
import io.peekandpoke.ultra.security.user.UserId
import java.util.Base64
import java.util.Date

/**
 * The gate that authenticates a token before anything parses it.
 *
 * The tests that matter most are the first two: they are the exact probes that showed the removed
 * `java-jwt` parsing unauthenticated JSON, and they must fail on the MAC instead. The rest exist so
 * that the gate cannot reject anything the old issuer would have accepted — a gate that is subtly
 * stricter than the issuer breaks every login, and one that is looser is pointless.
 */
class JwtSignatureGateSpec : StringSpec({

    val secret = "test-signing-key-for-the-gate-spec"

    val config = JwtConfig(
        signingKey = Redacted(secret),
        issuer = "test-issuer",
        audience = "test-audience",
        permissionsNs = "permissions",
        userNs = "user",
    )

    val generator = JwtGenerator(config)
    val gate = JwtSignatureGate(secret)

    val b64 = Base64.getUrlEncoder().withoutPadding()

    fun handMadeToken(header: String, payload: String, signature: String = "not-a-valid-signature") =
        "${b64.encodeToString(header.toByteArray())}.${b64.encodeToString(payload.toByteArray())}.$signature"

    /** A genuine token, produced by the very code path that signs in production. */
    fun realToken(): String = generator.createJwt(user = JwtUserData(id = UserId("u1"), desc = "d", type = "t"))

    // ── the property this exists for ────────────────────────────────────────────────────────────────

    "a malformed payload is rejected WITHOUT being parsed" {
        val thrown = shouldThrow<JwtVerificationException> {
            generator.verify(handMadeToken("""{"alg":"HS512","typ":"JWT"}""", """{"sub": {{{ """))
        }

        // If anything parsed before the MAC, this malformed payload would surface as the decode
        // rejection ("payload is not a JSON object") instead of a gate rejection. The TYPE is what
        // pins the order of the two steps.
        thrown.shouldBeInstanceOf<JwtSignatureGate.Rejected>()
    }

    "a malformed header is rejected WITHOUT being parsed" {
        val thrown = shouldThrow<JwtVerificationException> {
            generator.verify(handMadeToken("""{"alg": [[[ """, """{"sub":"x"}"""))
        }

        thrown.shouldBeInstanceOf<JwtSignatureGate.Rejected>()
    }

    "an oversized token is rejected before it is hashed, let alone parsed" {
        // Under java-jwt this 20 MB string was fully parsed and allocated, and only THEN failed the
        // signature check. It does not even reach the MAC.
        val huge = handMadeToken("""{"alg":"HS512","typ":"JWT"}""", """{"s":"""" + "A".repeat(20_000_000) + """"}""")

        shouldThrow<JwtSignatureGate.Rejected> { generator.verify(huge) }
            .message shouldBe "Token exceeds the maximum accepted length"
    }

    "a deeply nested payload never reaches a parser" {
        val nested = handMadeToken("""{"alg":"HS512","typ":"JWT"}""", "[".repeat(10_000) + "]".repeat(10_000))

        shouldThrow<JwtSignatureGate.Rejected> { generator.verify(nested) }
    }

    // ── the gate must not be stricter than the issuer ───────────────────────────────────────────────

    "a genuine token passes the gate and still verifies" {
        // Wire compatibility: the gate must compute the SAME signing input as the issuer, or every
        // real token breaks. This is the test that catches a re-encoding mistake.
        val token = realToken()

        gate.check(token)

        generator.verify(token).subject shouldBe "u1"
        // tryVerify must agree with verify — compared by a claim, since the decoder has no equals()
        generator.tryVerify(token)?.subject shouldBe "u1"
    }

    "a token minted by java-jwt 4.5.2 still passes — wire compatibility" {
        // Hard-coded fixture generated by the removed library (2026-07-31) with this spec's config,
        // pinned so the gate can never drift from what the old issuer signed: tokens issued before
        // the swap must keep verifying after it.
        val libraryMinted = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9." +
            "eyJpc3MiOiJ0ZXN0LWlzc3VlciIsImF1ZCI6InRlc3QtYXVkaWVuY2UiLCJzdWIiOiJ1MiJ9." +
            "WAEiEHk-XsqCQMEkzJKxyexaBVQLzIGQRoH9BQQFr0FbIzpKZ4k0k3Vfa27HBfZ2dU5Agd3fgCZHHGddX3EE5w"

        gate.check(libraryMinted)

        generator.verify(libraryMinted).subject shouldBe "u2"
    }

    // ── rejections ──────────────────────────────────────────────────────────────────────────────────

    "a tampered payload is rejected" {
        val real = realToken()
        val parts = real.split(".")
        val tampered = "${parts[0]}.${b64.encodeToString("""{"sub":"admin"}""".toByteArray())}.${parts[2]}"

        shouldThrow<JwtSignatureGate.Rejected> { gate.check(tampered) }
    }

    "a tampered signature is rejected" {
        val real = realToken()
        val lastDot = real.lastIndexOf('.')

        // Flip a character in the MIDDLE of the signature, not the last one. A 64-byte HMAC-SHA512
        // encodes to 86 base64url characters = 516 bits, so the FINAL character carries 4 unused bits:
        // changing it can leave the decoded signature bytes identical, and the token still verifies —
        // correctly, since the bytes are what authenticate. An earlier version of this test flipped the
        // last character and failed for exactly that reason.
        val at = lastDot + 1 + (real.length - lastDot - 1) / 2
        val flipped = real.replaceRange(at, at + 1, if (real[at] == 'A') "B" else "A")

        // Guard on the DECODED BYTES, not on the strings. `flipped != real` is true by construction and
        // would still pass if `at` were moved back onto the final character — the exact bug the comment
        // above records — leaving only the real assertion to fail, with a misleading message.
        withClue("flipping a middle signature character must change the decoded bytes") {
            val decode = { t: String -> Base64.getUrlDecoder().decode(t.substringAfterLast('.')) }
            decode(flipped).contentEquals(decode(real)) shouldBe false
        }

        shouldThrow<JwtSignatureGate.Rejected> { gate.check(flipped) }
    }

    "the wrong key is rejected" {
        shouldThrow<JwtSignatureGate.Rejected> { JwtSignatureGate("a-different-key").check(realToken()) }
    }

    "structurally broken tokens are rejected, not crashed on" {
        // Each of these would be an exception of some other type if the gate did not guard the shape.
        listOf(
            "" to "empty",
            "." to "just a dot",
            "onlyonesegment" to "no dots",
            "header.payload." to "empty signature",
            ".payload.signature" to "empty header",
            "a.b.!!!not-base64!!!" to "signature is not base64url",
        ).forEach { (token, why) ->
            withClue(why) { shouldThrow<JwtSignatureGate.Rejected> { gate.check(token) } }
        }
    }

    // ── algorithm confusion is unreachable, not merely blocked ──────────────────────────────────────

    "alg:none in the header buys nothing, because the header is never read" {
        // The classic attack: claim `none` and send no signature. The gate does not consult `alg` at
        // all — the token dies because it carries no valid HMAC512, which is a stronger property than
        // rejecting the algorithm by name.
        shouldThrow<JwtSignatureGate.Rejected> {
            generator.verify(handMadeToken("""{"alg":"none","typ":"JWT"}""", """{"sub":"admin"}""", ""))
        }

        shouldThrow<JwtSignatureGate.Rejected> {
            gate.check("""${b64.encodeToString("""{"alg":"none"}""".toByteArray())}.${b64.encodeToString("""{"sub":"admin"}""".toByteArray())}.x""")
        }
    }

    "claiming a weaker algorithm in the header buys nothing either" {
        // HS256-signed token (minted by java-jwt with this spec's secret) presented to the HS512
        // gate: rejected on the MAC.
        val hs256 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9." +
            "eyJzdWIiOiJhZG1pbiJ9." +
            "l7BEL8MzylhbmbAVtDyLfm2M5jmjCJXzlgHrvXBpvgc"

        shouldThrow<JwtSignatureGate.Rejected> { gate.check(hs256) }
    }

    "a valid MAC with a foreign header is accepted — the header is never read" {
        // The one measured divergence from java-jwt, taken deliberately: the library ALSO rejected a
        // valid-MAC token whose header names a different algorithm (AlgorithmMismatchException). Only
        // the signing-key holder can craft this shape, and the key holder can mint arbitrary valid
        // tokens anyway — so nothing is defended by rejecting it, and the header stays unparsed.
        val payload = """{"iss":"${config.issuer}","aud":"${config.audience}","sub":"u5"}"""
        val signingInput = "${b64.encodeToString("""{"alg":"none"}""".toByteArray())}.${b64.encodeToString(payload.toByteArray())}"
        val token = "$signingInput.${b64.encodeToString(gate.mac(signingInput))}"

        generator.verify(token).subject shouldBe "u5"
    }

    // ── claim validation still does its job afterwards ──────────────────────────────────────────────

    "the gate does not replace claim validation — a wrong issuer still fails" {
        // Correctly signed with the SAME key, so it passes the gate; claim validation must reject it.
        val wrongIssuer = JwtGenerator(config.copy(issuer = "somebody-else"))
            .createJwt(user = JwtUserData(id = UserId("u3"), desc = "d", type = "t"))

        gate.check(wrongIssuer)

        val thrown = shouldThrow<JwtVerificationException> { generator.verify(wrongIssuer) }
        (thrown is JwtSignatureGate.Rejected) shouldBe false
    }

    "an expired token passes the gate and is rejected by the claim validation" {
        val expired = generator.createJwt(user = JwtUserData(id = UserId("u4"), desc = "d", type = "t")) {
            withExpiresAt(Date(0))
        }

        gate.check(expired)

        shouldThrow<JwtVerificationException> { generator.verify(expired) }
    }

    "tryVerify still returns null rather than throwing, for gate rejections too" {
        // Rejected extends JwtVerificationException precisely so this keeps working.
        generator.tryVerify(handMadeToken("""{"alg":"HS512"}""", """{"sub": {{{ """)) shouldBe null
        generator.tryVerify("garbage") shouldBe null
    }
})
