package io.peekandpoke.ultra.tooling.i18nfixture

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.peekandpoke.ultra.i18n.I18n
import io.peekandpoke.ultra.i18n.Locale

/**
 * End-to-end proof of the i18n plugin: the accessors and catalog used here are GENERATED by
 * `generateI18n` from `src/commonMain/i18n/messages.*.yaml` — if generation, srcDir wiring, or the
 * emitted code breaks, this module does not even compile.
 */
class I18nFixtureSpec : StringSpec({

    fun i18nFor(tag: String) = I18n(Locale.parse(tag), fallback = Locale("en")) {
        install(FixtureCatalog)
    }

    "generated accessor resolves in the selected language" {
        i18nFor("en").translate.fixture.hello(name = "X") shouldBe "Hello X!"
        i18nFor("de").translate.fixture.hello(name = "X") shouldBe "Hallo X!"
    }

    "regional variant wins for overridden keys and inherits the rest" {
        val ch = i18nFor("de-CH")
        ch.translate.fixture.hello(name = "X") shouldBe "Grüezi X!"
        ch.translate.fixture.plain() shouldBe "Nur Text" // inherited from base German
    }

    "plural accessor selects the right form" {
        i18nFor("en").translate.fixture.items(count = 1) shouldBe "1 item"
        i18nFor("en").translate.fixture.items(count = 5) shouldBe "5 items"
        i18nFor("de").translate.fixture.items(count = 5) shouldBe "5 Elemente"
    }

    "nested namespaces resolve" {
        i18nFor("en").translate.fixture.nested.deep(value = 42) shouldBe "Deep 42"
    }

    "keyword and hyphenated keys generate callable backtick-quoted accessors" {
        i18nFor("en").translate.fixture.`is`() shouldBe "reserved word key"
        i18nFor("de").translate.fixture.`greet-user`(`first-name` = "Sam") shouldBe "Hallo Sam"
    }

    "fallback chain reaches en for a language with no catalog" {
        i18nFor("fr").translate.fixture.plain() shouldBe "Just text"
    }
})
