package io.peekandpoke.funktor.codegen

import io.peekandpoke.ultra.codegen.sdk.TsSdkContributor
import io.peekandpoke.ultra.codegen.sdk.TsSdkEmitContext
import io.peekandpoke.ultra.codegen.ts.TsRuntime

/**
 * Ships the hand-written auth session runtime into the generated SDK.
 *
 * The auth API CLIENT is already generated by [RestApiTsContributor] — `signIn`, `refreshToken` and
 * the rest fall out of the route walk like any other feature. What cannot be generated is the
 * SESSION: where the token lives, how it reaches the transport, and how a view observes it. That is
 * behaviour, so it is hand-written, as `TsRuntime.Module.Auth`.
 *
 * The runtime itself lives in `ultra:codegen` because nothing in it is funktor-specific and because
 * `ts-verify` cannot see another module's resources. THIS class is the funktor-side decision about
 * when it ships, and the seam the login page and its route registration will attach to.
 *
 * **Emitted unconditionally.** Every funktor app has auth routes, and unlike the SSE parser this is
 * small and has no transitive weight. If a profile ever produces an SDK with no auth feature, this
 * should become conditional on the auth routes being reached — the same shape
 * [RestApiTsContributor] uses for `TsRuntime.Module.Sse`.
 *
 * Lives in `funktor:codegen` rather than in `funktor:auth` deliberately: this module is already
 * dev-time-only, whereas making `funktor:auth` depend on `ultra:codegen` would drag the generator
 * into a production artifact.
 */
class AuthTsContributor : TsSdkContributor {

    companion object {
        const val NAME: String = "funktor:auth"

    }

    override val name: String = NAME

    override fun emit(context: TsSdkEmitContext) {
        // The closure brings `runtime/http.ts` with it, which the REST contributor also ships —
        // runtime modules are planned with `out.shared`, so two contributors asking for the same one
        // dedupe instead of colliding.
        TsRuntime.emit(context.out, setOf(TsRuntime.Module.Auth, TsRuntime.Module.Login, TsRuntime.Module.Refresh))
    }
}
