package io.peekandpoke.funktor.codegen

import io.peekandpoke.funktor.rest.ApiFeature
import io.peekandpoke.ultra.codegen.sdk.TsSdkContributor
import io.peekandpoke.ultra.codegen.sdk.TsSdkEmitContext
import io.peekandpoke.ultra.codegen.sdk.TsSdkRegistry

/**
 * Ships the insights detail page, its collector tabs, and the shared UI primitives they render with.
 *
 * The insights API CLIENT is generated by [RestApiTsContributor] like any other feature. What cannot
 * be generated is the VIEW — which tab renders which collector, and what a request trace should look
 * like — so those are hand-written `.vue` resources and this class decides when they ship.
 *
 * **The resources live in this module, not in `funktor:insights`.** Settled 2026-08-02 by the
 * maintainer. They are generator INPUTS: no JVM code reads them and they never execute on a JVM, so
 * the runtime module boundary does not apply. The decisive argument is dependency direction — a
 * contributor may only emit resources on its OWN classpath, and contributors must live here (a
 * feature module depending on `ultra:codegen` would drag the generator into a production artifact).
 * Putting the resources in feature modules would therefore force `funktor:codegen` to depend on every
 * module that ships UI, an unbounded fan-in growing with each new page. `ts/runtime/auth.ts` in
 * `ultra:codegen` already set the precedent.
 *
 * The cost is honest and worth stating: a collector's wire shape and its tab now live in different
 * modules, with no compiler linking them. `funktor/insights/reference/TAB-SPECS.md` is the bridge.
 *
 * **This does not close the extension point.** `out.resource` reads the CONTRIBUTOR's classpath, so
 * an app defining its own collector ships its own tab from its own module and always could — an
 * application may depend on `ultra:codegen` freely; only published library modules must not.
 */
class InsightsTsContributor(
    private val features: Lazy<List<ApiFeature>>,
) : TsSdkContributor {

    companion object {
        const val NAME: String = "funktor:insights-ui"

        /**
         * The feature whose client the pages import.
         *
         * Matched by NAME rather than by type, because this module deliberately does not depend on
         * `funktor:insights` — see the class KDoc. The coupling is checked rather than trusted; see
         * [emit].
         */
        private const val FEATURE_NAME: String = "Funktor Insights"

        /** What `InsightsListPage.vue` and `InsightsDetailPage.vue` import, verbatim. */
        private const val CLIENT_IMPORT: String = "funktorInsightsClient.ts"

        /**
         * Shared primitives, emitted at depth 1 as `ui/…`.
         *
         * **`sharedResource`, never `resource`.** Any module shipping components will want these, and
         * an exclusive claim would make the second one a hard error. Sharing also makes "the design
         * system ships iff something needs it" true by construction — nothing emits it on its own.
         */
        private val UI_FILES: List<String> = listOf(
            "theme.css",
            "types.ts",
            // How a page the ROUTER constructed reaches the app's config. Shared, because every
            // contributed page has the same problem: `mountAll` passes no props.
            "sdkContext.ts",
            "FactList.vue",
            "JsonTree.vue",
            "KeyValueTable.vue",
            "PreBlock.vue",
            "StatStrip.vue",
        )

        /** Insights' own files, emitted at depth 1 as `insights/…`. This module is the sole owner. */
        private val INSIGHTS_FILES: List<String> = listOf(
            "insights.css",
            "slices.ts",
            "RequestTab.vue",
            "ResponseTab.vue",
            "UserTab.vue",
            "RoutingTab.vue",
            "TemplateTab.vue",
            "LogTab.vue",
            "InsightsListPage.vue",
            "InsightsDetailPage.vue",
            "InsightsPage.vue",
        )

        /** Base layer: defines the custom properties everything else consumes. */
        private const val THEME_ORDER: Int = 0

        /** Feature layer, above the theme. */
        private const val INSIGHTS_ORDER: Int = 100
    }

    override val name: String = NAME

    /**
     * Emits nothing unless the insights feature is actually present.
     *
     * **Conditional, unlike [AuthTsContributor].** Every funktor app has auth; insights is opt-in, and
     * the pages import `../funktorInsightsClient.ts` — a file that exists only because
     * [RestApiTsContributor] walked this feature. Emitting them into an SDK without it would produce
     * TypeScript that cannot resolve its own imports, and the failure would surface in the consuming
     * app's build rather than here.
     *
     * **DEPTH 1 is not a style preference.** The components import `../models.ts`, `../ui/JsonTree.vue`
     * and the client above, so a `pages/insights/…` layout would break every one of them. The registry
     * takes an explicit component path precisely so nothing forces a convention.
     */
    override fun emit(context: TsSdkEmitContext) {
        val feature = features.value.firstOrNull { it.codeGenName == FEATURE_NAME } ?: return

        // The name match above is a string, so PROVE it still yields the file the components import.
        // If the feature is ever renamed, `RestApiTsContributor` emits a differently-named client and
        // these pages break — this turns that into a build failure here instead of a dangling import
        // discovered in someone's frontend.
        val clientFile = TsClientNames.clientFile(feature.codeGenName)

        check(clientFile == CLIENT_IMPORT) {
            "The insights components import '../$CLIENT_IMPORT', but feature " +
                    "'${feature.codeGenName}' now generates '$clientFile'. Renaming the feature " +
                    "renames its client, so the hand-written pages under " +
                    "'src/main/resources/ts/insights/' must be updated to match — or this contributor " +
                    "will ship TypeScript that cannot resolve its own imports."
        }

        UI_FILES.forEach { file ->
            context.out.sharedResource("ts/ui/$file", to = "ui/$file")
        }

        INSIGHTS_FILES.forEach { file ->
            context.out.resource("ts/insights/$file", to = "insights/$file")
        }

        context.registry.style(path = "ui/theme.css", order = THEME_ORDER)
        context.registry.style(path = "insights/insights.css", order = INSIGHTS_ORDER)

        context.registry.route(
            path = "/insights",
            component = "insights/InsightsPage.vue",
            requiresAuth = true,
            nav = TsSdkRegistry.Nav(label = "Insights", icon = "gauge", order = 10),
        )
    }
}
