package io.peekandpoke.funktor.insights.api

import io.peekandpoke.funktor.rest.ApiFeature
import io.peekandpoke.funktor.rest.ApiRoutes

/**
 * The only way to reach insights data.
 *
 * Deliberately ships **no hand-written `ApiClient`**, unlike every other funktor API module. That
 * pattern exists because Kraft frontends hand-wrote their clients; the TypeScript client for this one is
 * generated by `RestApiTsContributor`, so a checked-in Kotlin client would be the very thing codegen
 * exists to delete. The endpoint declarations therefore live on [InsightsApi] itself.
 */
class InsightsApiFeature : ApiFeature {

    /** Depot paths are `records-<date>/<file>.json`, so the record id arrives as two segments. */
    data class RecordParam(
        val bucket: String,
        val file: String,
    )

    override val name = "Insights"

    override val description = """
        Superuser-only access to recorded request insights.
    """.trimIndent()

    val insights = InsightsApi()

    override fun getRouteGroups(): List<ApiRoutes> = listOf(
        insights,
    )
}
