package io.peekandpoke.ultra.codegen.ts

import io.kotest.assertions.withClue
import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain

class TsBarrelEmitterSpec : FreeSpec() {

    init {
        "re-exports every emitted module" {
            val out = TsBarrelEmitter.emit(listOf("models.ts", "authClient.ts", "runtime/client.ts"))

            out shouldContain "export * from './models.ts'"
            out shouldContain "export * from './authClient.ts'"
            out shouldContain "export * from './runtime/client.ts'"
        }

        "never re-exports a .d.ts" {
            // A declaration file exports nothing to re-export, and `export * from './x.d.ts'` is not
            // a specifier TypeScript accepts. Added by /feature-review 2026-08-09: the filter existed
            // and NOTHING exercised it, so deleting it left every test green while every real SDK's
            // barrel gained `export * from './css-modules.d.ts'`.
            val out = TsBarrelEmitter.emit(
                listOf("models.ts", TsStylesEmitter.TYPES_PATH, "ui/other.d.ts")
            )

            out shouldNotContain ".d.ts"

            withClue("and the ordinary modules alongside it still are re-exported") {
                out shouldContain "export * from './models.ts'"
            }
        }

        "never re-exports itself" {
            // A module re-exporting itself is a circular import that resolves to nothing useful, and
            // the barrel is in the same entry list as everything else.
            val out = TsBarrelEmitter.emit(listOf("models.ts", TsBarrelEmitter.PATH))

            withClue("the barrel is in the input, so it must be filtered out by name") {
                out shouldNotContain "export * from './index.ts'"
            }

            out shouldContain "export * from './models.ts'"
        }

        "ignores non-TypeScript files" {
            // The output also carries samples, manifests and whatever a contributor plans.
            val out = TsBarrelEmitter.emit(listOf("models.ts", "manifest.json", "README.md", ".funktor-sdk"))

            out shouldContain "export * from './models.ts'"
            out shouldNotContain "manifest.json"
            out shouldNotContain "README.md"
        }

        "is SORTED and stable, because --check compares content" {
            // An unstable order makes `--check` report drift that is not real, which trains people to
            // ignore it — the one outcome that makes the flag worthless.
            val forwards = TsBarrelEmitter.emit(listOf("a.ts", "b.ts", "c.ts"))
            val backwards = TsBarrelEmitter.emit(listOf("c.ts", "a.ts", "b.ts"))

            forwards shouldBe backwards

            withClue("and sorted, not merely deterministic") {
                val order = listOf("a.ts", "b.ts", "c.ts").map { forwards.indexOf("'./$it'") }

                order shouldBe order.sorted()
            }
        }

        "a duplicate path is emitted once" {
            val out = TsBarrelEmitter.emit(listOf("models.ts", "models.ts"))

            Regex("export \\* from './models\\.ts'").findAll(out).count() shouldBe 1
        }

        "an empty SDK still produces a valid module" {
            // `export {}` is not needed: a file with only a comment is still a module under
            // `isolatedModules` as long as nothing imports a binding from it. What must NOT happen is
            // a crash or a half-written file.
            val out = TsBarrelEmitter.emit(emptyList())

            out shouldContain "Generated by ultra:codegen"
            out shouldNotContain "export *"
        }
    }
}
