package io.peekandpoke.ultra.tooling.i18n

import io.peekandpoke.ultra.i18n.model.I18nMessage
import io.peekandpoke.ultra.i18n.model.I18nModelBuilder
import io.peekandpoke.ultra.i18n.model.I18nNamespace
import io.peekandpoke.ultra.i18n.model.I18nNode
import io.peekandpoke.ultra.i18n.model.LocaleCatalog

/**
 * Emits Kotlin source from parsed catalogs (D5/D6 split):
 *  - a baked `<Module>Catalog : I18nCatalog` object holding every locale's data, and
 *  - an accessors file: a receiver class + `I18nTranslate` extension property per namespace, and a
 *    non-inline top-level extension function per message.
 *
 * Message accessors force named arguments via a leading `vararg _: Unit` — a parameter after a vararg
 * must be passed by name — so reordering or renaming a placeholder surfaces at the call site instead
 * of silently mis-binding.
 *
 * All names that originate from catalog content are run through [kotlinMemberName]/[kotlinClassPart]
 * (whitelist + backtick, reject on violation) and all baked strings through [escape], so crafted
 * catalog keys can neither inject code nor corrupt a string literal.
 */
object KotlinEmitter {

    private const val I18N_PKG = "io.peekandpoke.ultra.i18n"

    fun emit(
        config: I18nGenConfig,
        fallback: LocaleCatalog,
        allLocales: List<LocaleCatalog>,
    ): List<GeneratedFile> {
        val tree = I18nModelBuilder.build(fallback)
        return listOf(
            GeneratedFile(config.catalogFileName, emitCatalog(config, allLocales)),
            GeneratedFile(config.accessorsFileName, emitAccessors(config, tree)),
        )
    }

    // --- Baked catalog ---

    private fun emitCatalog(config: I18nGenConfig, locales: List<LocaleCatalog>): String {
        val w = CodeWriter()
        w.line("package ${config.packageName}").line()
        w.line("import $I18N_PKG.I18nCatalog")
        w.line("import $I18N_PKG.Locale").line()
        w.line("// Generated by the i18n codegen. Do not edit.").line()
        w.line("object ${config.catalogObjectName} : I18nCatalog {").indented {
            line("private val data: Map<String, Map<String, String>> = mapOf(").indented {
                locales.forEach { loc ->
                    line("\"${escape(loc.localeTag)}\" to mapOf(").indented {
                        loc.entries.forEach { (key, value) ->
                            line("\"${escape(key)}\" to \"${escape(value)}\",")
                        }
                    }
                    line("),")
                }
            }
            line(")").line()
            line("override fun template(key: String, locale: Locale): String? =").indented {
                line("data[locale.tag]?.get(key)")
            }
        }
        w.line("}")
        return w.toString()
    }

    // --- Accessors ---

    private fun emitAccessors(config: I18nGenConfig, tree: List<I18nNode>): String {
        checkClassNameUniqueness(tree)
        val w = CodeWriter()
        w.line("package ${config.packageName}").line()
        w.line("import $I18N_PKG.I18n")
        w.line("import $I18N_PKG.I18nTranslate").line()
        w.line("// Generated by the i18n codegen. Do not edit.").line()
        tree.forEach { node -> emitNode(w, node, receiverType = "I18nTranslate", namePath = emptyList()) }
        return w.toString()
    }

    private fun emitNode(w: CodeWriter, node: I18nNode, receiverType: String, namePath: List<String>) {
        when (node) {
            is I18nMessage -> emitAccessor(w, node, receiverType)
            is I18nNamespace -> {
                val path = namePath + node.name
                val className = classNameFor(path)
                val property = kotlinMemberName(node.name, "namespace")
                w.line("class $className(val i18n: I18n)")
                w.line("val $receiverType.$property: $className get() = $className(i18n)")
                w.line()
                node.children.forEach { child -> emitNode(w, child, className, path) }
            }
        }
    }

    private fun emitAccessor(w: CodeWriter, msg: I18nMessage, receiverType: String) {
        val fnName = kotlinMemberName(msg.name, "message name")
        val placeholderIds = msg.placeholders.map { it to kotlinMemberName(it, "placeholder") }

        val params = buildList {
            if (msg.plural) add("count: Int")
            placeholderIds.forEach { (_, id) -> add("$id: Any?") }
        }
        val signature = if (params.isEmpty()) {
            "fun $receiverType.$fnName(): String ="
        } else {
            "fun $receiverType.$fnName(vararg forcedNamed: Unit, ${params.joinToString(", ")}): String ="
        }
        w.line(signature)

        val key = escape(msg.key)
        val argsMap = placeholderIds.joinToString(", ") { (raw, id) -> "\"${escape(raw)}\" to $id" }
        val body = when {
            msg.plural && placeholderIds.isEmpty() -> "i18n.resolvePlural(\"$key\", count, emptyMap())"
            msg.plural -> "i18n.resolvePlural(\"$key\", count, mapOf($argsMap))"
            placeholderIds.isEmpty() -> "i18n.resolve(\"$key\")"
            else -> "i18n.resolve(\"$key\", mapOf($argsMap))"
        }
        w.indented { line(body) }
        w.line()
    }

    private fun classNameFor(path: List<String>): String =
        path.joinToString("") { kotlinClassPart(it, "namespace") } + "I18n"

    /** Rejects two namespaces that would emit the same receiver class name (a duplicate declaration). */
    private fun checkClassNameUniqueness(tree: List<I18nNode>) {
        val names = mutableListOf<String>()
        fun walk(nodes: List<I18nNode>, path: List<String>) {
            nodes.forEach { node ->
                if (node is I18nNamespace) {
                    val p = path + node.name
                    names += classNameFor(p)
                    walk(node.children, p)
                }
            }
        }
        walk(tree, emptyList())
        val dupes = names.groupingBy { it }.eachCount().filterValues { it > 1 }.keys
        require(dupes.isEmpty()) {
            "i18n namespace class-name collision: ${dupes.joinToString()} — rename a colliding namespace."
        }
    }

    /** Escapes a raw string for embedding in a Kotlin double-quoted string literal. */
    private fun escape(s: String): String = buildString {
        s.forEach { c ->
            when (c) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '$' -> append("\\\$")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(c)
            }
        }
    }
}
